"""empty message

Revision ID: a404a242c81b
Revises: 272caeb52873
Create Date: 2025-11-16 03:27:03.320311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a404a242c81b'
down_revision: Union[str, None] = '272caeb52873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('scan', sa.Column('target', sa.String(), nullable=False))
    op.add_column('scan', sa.Column('nmap_output', sa.Text(), nullable=False))
    op.add_column('scan', sa.Column('nuclei_output', sa.Text(), nullable=False))
    op.add_column('scan', sa.Column('exploit_log', sa.Text(), nullable=False))
    op.add_column('scan', sa.Column('report_content', sa.Text(), nullable=False))
    op.create_index(op.f('ix_scan_target'), 'scan', ['target'], unique=False)
    op.drop_column('scan', 'host')
    op.drop_column('scan', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scan', sa.Column('host', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scan_target'), table_name='scan')
    op.drop_column('scan', 'report_content')
    op.drop_column('scan', 'exploit_log')
    op.drop_column('scan', 'nuclei_output')
    op.drop_column('scan', 'nmap_output')
    op.drop_column('scan', 'target')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
